---
output: pdf_document
---
Barplot Analysis of Cushing Results
=======================================

This script produces bar plots. And it was last run on `r date()`.

```{r file-input, echo=FALSE, warning=FALSE}
filename <- "../data/processed/rpkm_table.csv"
liver.filename <- "../data/processed/Liver_Interaction_DESeqResultsProteinCodingOnly.csv"
wat.filename <- "../data/processed/WAT_Interaction_DESeqResultsProteinCodingOnly.csv"
#read in the file
normalized.data <- read.csv(filename, row.names='X')
liver.data <- read.csv(liver.filename, row.names='X')
wat.data <- read.csv(wat.filename, row.names='X')
mapping <- read.csv("../data/raw/Sample_mapping.csv")

#Making Normal and Vehicle as reference groups
mapping$Diet <- relevel(mapping$Diet, ref="Normal")
mapping$Drug <- ifelse(mapping$Treatment=="vehicle", "Vehicle", "GTX")
mapping$Drug <- as.factor(mapping$Drug)
mapping$Diet <- relevel(mapping$Drug, ref="Vehicle")

#replace the .txt in column names to empty space
colnames(normalized.data) <- gsub(pattern = ".txt", replacement = "", x = colnames(normalized.data), fixed = TRUE)

#Making Liver and WAT rpkm data sets
mapping.liver <- mapping[mapping$Tissue=="Liver",]
mapping.wat <- mapping[mapping$Tissue=="WAT",]

normalized.liver <- normalized.data[,colnames(normalized.data) %in% mapping.liver$Sample]
normalized.wat <- normalized.data[,colnames(normalized.data) %in% mapping.wat$Sample]

#get gene names for transcripts
library(biomaRt)
mart = useMart("ENSEMBL_MART_ENSEMBL", host="dec2014.archive.ensembl.org")
ensembl = useDataset('mmusculus_gene_ensembl',mart=mart)
gene.data <- getBM(attributes=c('ensembl_gene_id', 'external_gene_name'), 
                    filters = 'ensembl_gene_id',
                    values = rownames(normalized.data), mart = ensembl)
rpkm.data <- merge(normalized.data, gene.data, by.x='row.names', by.y='ensembl_gene_id') 
rpkm.data.unique <- rpkm.data[!duplicated(rpkm.data$external_gene_name),]
rownames(rpkm.data.unique) <- rpkm.data.unique$external_gene_name
rpkm.data.unique <- rpkm.data.unique[,-1]

rpkm.liver <- rpkm.data.unique[,colnames(rpkm.data.unique) %in% mapping.liver$Sample]
rpkm.liver$external_gene_name <- rpkm.data.unique$external_gene_name
rpkm.wat <- rpkm.data.unique[,colnames(rpkm.data.unique) %in% mapping.wat$Sample]
rpkm.wat$external_gene_name <- rpkm.data.unique$external_gene_name

#put the data in long format
library(reshape2)  
rpkm.long.liver <- reshape(rpkm.liver, direction="long", varying=list(names(rpkm.liver)[1:9]), v.names="Expression", idvar="external_gene_name", timevar="Diet_Drug", ids=rownames(rpkm.liver), times=c(rep('Normal_Vehicle',3),rep("HFD_Vehicle",3), rep("HFD_GTX",3)))

rpkm.long.wat <- reshape(rpkm.wat, direction="long", varying=list(names(rpkm.wat)[1:9]), v.names="Expression", idvar="external_gene_name", timevar="Diet_Drug", ids=rownames(rpkm.wat), times=c(rep('Normal_Vehicle',3),rep("HFD_Vehicle",3), rep("HFD_GTX",3)))


#calculate standard error
library(plyr)
rpkm.liver.se <- ddply(rpkm.long.liver, .(external_gene_name,Diet_Drug), summarise, se = sd(Expression, na.rm=T)/sqrt(length(Expression)), mean_Expression = mean(Expression, na.rm=T))

rpkm.wat.se <- ddply(rpkm.long.wat, .(external_gene_name,Diet_Drug), summarise, se = sd(Expression, na.rm=T)/sqrt(length(Expression)), mean_Expression = mean(Expression, na.rm=T))

rpkm.liver.se$Diet_Drug <- as.factor(rpkm.liver.se$Diet_Drug)
rpkm.wat.se$Diet_Drug <- as.factor(rpkm.wat.se$Diet_Drug)

rpkm.liver.se <- rpkm.liver.se[order(rpkm.liver.se$external_gene_name, rpkm.liver.se$Diet_Drug, decreasing=T),]
rpkm.wat.se <- rpkm.wat.se[order(rpkm.wat.se$external_gene_name, rpkm.wat.se$Diet_Drug, decreasing=T),]

```


```{r grouped-plots, dev=c('png','pdf'), echo=FALSE, fig.show='asis' }
library(ggplot2)
adipocytes <- c("Nrg4", "Ucp1", "Tmem120b", "Adrb3","Aqp7", "Gpr81", "Slc27a1", "Slc7a10", "Epsti1", "Cited1", "Fabp4")
brown_fat <- c("Ucp1", "Gpr119", "Tspan18", "P2rx5", "Zic1", "Lhx8", "Pat2", "Ebf3", "Prdm16", "Ppargc1a", 'Eva', 'Fbxo31', 'Pdk4', 'Acot2', 'Hsbp7', 'Slc29a1', 'Oplah' )
white_fat <- c("Asc1", "Slc7a10", "Tmem26", "Shox2", "Hoxc8","Hoxc9", "Adpioq", "Fbxo31", "Fabp3", "Mpzl2")
beige_fat <- c('Tbx1', 'Tmem26', 'Tnfrsf9', 'Irx3', 'Irx5', 'Klhl13', 'Cd40','Ear2','Cd137','Sp100','Tbx1','Slc27a1', 'Pat2')
hormones <- c('Lepr')
cortisol_signaling <-  c("Hsd11b2","Nr3c1","Nr3c2")
hsd11b1 <- "Hsd11b1"
lipolysis <- c("Abhd5", "Acvr1c", "Pnpla1")
lipid_metabolism <- c('Dhcr24','Tfcp2l1','Pnpla3','Dhcr7','Pcyt2','Cyp7b1','Hpgd','Plce1','Idi1','Npc1l1','Pdss2')
unsat_FA <- c("Elovl5", "Elovl6", "Fads1", "Fads2", "Hsd17b12", "Acox1", "Hadha", "Pecr")
adipocyte_regulator <- "Ube2i"

wnt <- c("Wnt1", "Wnt10b", "Wnt3a", "Wnt5a", "Wnt5b")
ppar_genes <- c("Ppara","Ppard","Pparg","Ppargc1a","Ppargc1b", "Fabp1", "Fas", "Apt1", "Cept1", "Tnf", "Il6", "Pck1", "Pck2", "Hadha")
adipocyte1 <- c("Acacb","Adrb2","Angpt2","Axin1","Bmp2","Bmp4", "Bmp7","Ccnd1", "Cdk4","Cdkn1a", "Cdkn1b", "Cebpb","Cfd", "Creb1","Ddit3","Dio2","Dkk1")
adipocyte2 <- c("E2f1","Egr2","Fabp4","Fasn","Fgf1","Fgf10","Fgf2","Foxc2","Foxo1","Gata2","Gata3","Hes1","Insr","Irs1","Irs2","Jun","Klf15","Klf2","Klf4","Lepr","Lmna","Lrp5", "Mapk14", "Ncoa2","Ncor2","Nr0b2")
adipocyte3 <- c("Hsdd11b1","Nr1h3","Nrf1", "Rb1","Runx1t1","Rxra","Sfrp1","Sirt1","Sirt2","Sirt3","Slc2a4","Src","Srebf1","Taz","Tcf7l2","Tsc22d3","Twist1", "Vdr")

genes_exp_more100 <- c( "Agt", "Cebpa","Agpat2", 'Fads1','Fads2')
genes_exp_less100 <- c("Fasn", "Pck", "Dgat2",  "Mgll", "Pnpla2")
genes_exp_less40 <- c("Lep", "Adipoq", "Fabp4", "Lpl", "Lipe", "Cfd", 'Adrb3', "Fzd4", 'Cd300lg', "Retn", "Sfrp5", "Adig")
genes_exp_1000 <- c("Scd1")

nk_cells <- c('Ifng','Lat','Ncr1', 'Vav3','Shc2', 'Klrc1', 'Sh2d1a', 'Cd247', 'Fcer1g','Cd48','Pik3r5','Rac2','Lck','Tyrobp','Klrk1','Plcg2','Shc4','Pack1','Icam1','Itgal','')
peroxisome <- c('Pex11b','Baat','Hao1','Acox2','Agxt')
  
gene.data.name <- c('cortisol_signaling', 'adipocytes', 'brown_fat', 'white_fat', 'beige_fat', 'lipolysis', 'lipid_metabolism', 'unsat_FA', 'adipocyte_regulator', 'wnt', 'ppar_genes', 'adipocyte1', 'adipocyte2', 'adipocyte3', 'hormones', 'genes_exp_less100', 'genes_exp_more100', 'genes_exp_less40', 'genes_exp_1000','nk_cells','peroxisome')



for (name in gene.data.name){
  #name <- as.name(name) #convert string to variable name
  gene.data <- rpkm.liver.se[rpkm.liver.se$external_gene_name%in%eval(as.name(name)),]
  gene.data$external_gene_name <- factor(gene.data$external_gene_name, levels=eval(as.name(name)))
  gene.data$Diet_Drug <- factor(gene.data$Diet_Drug, levels=c("Normal_Vehicle", "HFD_Vehicle", "HFD_GTX"))
  
  ggplot(gene.data, aes(x=external_gene_name, y=mean_Expression, fill=Diet_Drug))+ 
    #this line together with show_guide=F and the element_rect=black get rid of the slash in legend box
    geom_bar(stat="identity", width=.8, position=position_dodge(width=.8)) +
    geom_bar(stat="identity",width=.8, position=position_dodge(width=.8), col="black", show_guide=F) +
    geom_errorbar(position=position_dodge(width=.8), aes(ymin=mean_Expression-se, ymax=mean_Expression+se), width=.2)+
    theme_bw()+theme(axis.text.x=element_text(angle=90))+xlab("")+ ylab("mRNA Expression (RPKM)") +
    theme(panel.grid.minor = element_blank()) + theme(panel.grid.major = element_blank()) + 
    theme(panel.border=element_blank())+ 
    theme(axis.line = element_line(color = 'black')) +
    scale_fill_grey(start = 0.3, end = .9, guide=guide_legend()) +
    #guides(fill = guide_legend(keywidth = .5, keyheight = .5)) +
    theme(text = element_text(size=20), axis.text.x = element_text(angle=70,hjust=.5,vjust=.5)) +
    theme(legend.position=c(.75,.90), legend.title=element_blank(), legend.key=element_rect(color="black"))   + ggtitle(name)
    
  ggsave(filename=paste('figures/Liver-', name, '-barplot.pdf',sep=""))
}

biocarta_ppara <- c('Fabp1','Apoa1','Apoa2',  'Nr2f1',	'Ptgs2',	'Pik3r1',	'Myc',	'Jun',	'Ppargc1a',	'Ppara',	'Prkar1b',	'Nrip1',	'Ncoa1',	'Tnf',	'Stat5a',	'Rxra',	'Ncor1',	'Stat5b',	'Nr0b2',	'Cd36',	'Ep300',	'Dusp1',	'Prkar2b')
bp_lipid_transport <- c('Apof', 'Apoc3', 'Apoa1', 'Apoa2', 'Lcat', 'Slco2a1', 'Ldlr', 'Apoe', 'Tspo', 'Ppara')
go_peroxisome <-c('Pex11b', 'Hao1', 'Agxt', 'Acot4', 'Slc27a2', 'Phyh', 'Ech1', 'Abcd2', 'Scp2', 'Mlycd', 'Amacr', 'Pex1', 'Pex19', 'Pxmp4', 'Acad11', 'Isoc1', 'Pex13', 'Pex6')
               
REACTOME_BILE_SALT_METABOLISM <- c('Cyp7a1', 'Baat', 'Slc27a5', 'Slc10a1', 'Alb', 'Acox2', 'Abcb11', 'Cyp8b1', 'Slc27a2', 'Akr1d1', 'Cyp27a1', 'Hsd3b7', 'Cyp7b1')
bile_salt_axis1 <- c('Alb', 'Cyp27a1', 'Hsd3b7')
REACTOME_BCAA_CATABOLISM <- c('Ivd', 'Mccc1', 'Dbt', 'Bcat2','Bckdhb', 'Acadsb', 'Aldh6a1', 'Auh', 'Mccc2', 'Hibch', 'Bckdha', 'Acat1')
REACTOME_PPARA_ACTIVATES_GENE_EXPRESSION <- c('Cyp7a1', 'Apoa5', 'Fabp1', 'Apoa1', 'Apoa2', 'Agt', 'Pparg', 'Slc27a1', 'Ctgf', 'Gos2', 'Ppargc1b', 'Alas1', 'Tead1', 'Trib3', 'Abcb4', 'Ppargc1a', 'Ppara', 'Hmgcs2', 'Acadm', 'Yap1', 'Ncoa1', 'Cpt2', 'Tead4', 'Rxra', 'Nr1d1')
REACTOME_PEROXISOMAL_LIPID<- c('Acox2', 'Slc27a2', 'Idh1', 'Phyh', 'Scp2', 'Amacr')
                                 
KEGG_PPAR_SIGNALING_PATHWAY <-c('Fabp2', 'Cyp7a1', 'Apoa5', 'Ucp1', 'Slc27a5', 'Apoc3', 'Fabp1', 'Apoa1', 'Apoa2', 'Acox2',  'Adipoq', 'Slc27a2', 'Ppara', 'Hmgcs2', 'Acadm', 'Fabp4', 'Scp2',	'Pck1', 'Agt', 'Ctgf', 'Gos2', 'Ppargc1b', 'Alas1', 'Tead1', 'Tead4', 'Trib3', 'Abcb4', 'Ppargc1a', 'Yap1', 'Ncoa1', 'Cpt2', 'Rxra', 'Nr1d1', 'Ilk')	

figure3 <- c("Mylk2")
gene.data.name <- c('biocarta_ppara','bp_lipid_transport','go_peroxisome', 'REACTOME_BILE_SALT_METABOLISM', 'REACTOME_BCAA_CATABOLISM', 'REACTOME_PPARA_ACTIVATES_GENE_EXPRESSION', 'REACTOME_PEROXISOMAL_LIPID', 'KEGG_PPAR_SIGNALING_PATHWAY', 'KEGG_PPAR_SIGNALING_PATHWAY', 'ppar_sig_axis2', 'ppar_sig_axis3', 'figure3')
#gene.data.name <- c('KEGG_PPAR_SIGNALING_PATHWAY', 'ppar_sig_axis2', 'ppar_sig_axis3', 'figure3')

###Bar plots for WAT####
for (name in gene.data.name){
  #name <- as.name(name) #convert string to variable name
  gene.data <- rpkm.wat.se[rpkm.wat.se$external_gene_name%in%eval(as.name(name)),]
  gene.data$external_gene_name <- factor(gene.data$external_gene_name, levels=eval(as.name(name)))
  gene.data$Diet_Drug <- factor(gene.data$Diet_Drug, levels=c("Normal_Vehicle", "HFD_Vehicle", "HFD_GTX"))
  ggplot(gene.data, aes(x=external_gene_name, y=mean_Expression, fill=Diet_Drug))+ 
    #this line together with show_guide=F and the element_rect=black get rid of the slash in legend box
    geom_bar(stat="identity", width=.8, position=position_dodge(width=.8)) +
    geom_bar(stat="identity",width=.8, position=position_dodge(width=.8), col="black", show_guide=F) +
    geom_errorbar(position=position_dodge(width=.8), aes(ymin=mean_Expression-se, ymax=mean_Expression+se), width=.2)+
    theme_bw()+theme(axis.text.x=element_text(angle=90))+xlab("")+ ylab("mRNA Expression (RPKM)") +
    theme(panel.grid.minor = element_blank()) + theme(panel.grid.major = element_blank()) + 
    theme(panel.border=element_blank())+ 
    theme(axis.line = element_line(color = 'black')) +
    #scale_fill_grey(start = 0.3, end = .9, guide=guide_legend()) +
    #guides(fill = guide_legend(keywidth = .5, keyheight = .5)) +
    theme(text = element_text(size=20), axis.text.x = element_text(angle=70,hjust=.5,vjust=.5)) +
    theme(legend.position=c(.25,.90), legend.title=element_blank(), legend.key=element_rect(color="black"))   + ggtitle(name)+
    #this below line changes the color of the bars.
    scale_fill_manual(values=c('#0080FF','#E69F00','#999999'))
  ggsave(filename=paste('figures/WAT-', name, '-barplot.pdf',sep=""))
}
```

```{r plot_with_different_axis_scale, echo=FALSE}
#Create a function that will draw into different y-axis scales.
twocoordinate <- function(list_name, index){
  require(ggplot2)
  #l.gene.data <- rpkm.wat.se[rpkm.wat.se$external_gene_name%in%eval(LHS),]
  #l.gene.data$external_gene_name<- factor(l.gene.data$external_gene_name, levels=eval(LHS))
  
  #r.gene.data <- rpkm.wat.se[rpkm.wat.se$external_gene_name%in%eval(RHS),]
  #r.gene.data$external_gene_name<- factor(r.gene.data$external_gene_name, levels=eval(RHS))
  
  gene.data <- rpkm.wat.se[rpkm.wat.se$external_gene_name%in%eval(list_name),]
  gene.data$external_gene_name <- factor(gene.data$external_gene_name, levels=eval(list_name))
  gene.data$Diet_Drug <- factor(gene.data$Diet_Drug, levels=c("Normal_Vehicle", "HFD_Vehicle", "HFD_GTX"))
  gene.data$index <- index
  print(gene.data)
  d <- ggplot(gene.data, aes(x=external_gene_name, y=mean_Expression, fill=Diet_Drug)) 
  d+geom_bar(stat="identity",width=.8, position=position_dodge(width=.8), col="black", show_guide=F) + 
  geom_errorbar(position=position_dodge(width=.8), aes(ymin=mean_Expression-se, ymax=mean_Expression+se), width=.2)+
  facet_wrap(~index , scales = "free") +
  theme_bw()+ ylab("mRNA Expression (RPKM)") +xlab("")+
  theme(panel.grid.minor = element_blank()) + theme(panel.grid.major = element_blank()) + 
  theme(panel.border=element_blank())+ 
  theme(axis.line = element_line(color = 'black')) +
  scale_fill_manual(values=c('#0080FF','#E69F00','#999999')) +
  #scale_fill_grey(start = 0.3, end = .9, guide=guide_legend()) +
  #guides(fill = guide_legend(keywidth = .5, keyheight = .5)) +
  theme(text = element_text(size=20), axis.text.x = element_text(angle=70,hjust=.5,vjust=.5)) +
  theme(legend.position=c(.25,.90), legend.title=element_blank(), legend.key=element_rect(color="black")) 
  
  ggsave(filename=paste('figures/Twocord-', deparse(substitute(list_name)), '-barplot.pdf',sep=""))
}


ppar <- c('Adipoq', 'Fabp4', 'Pck1', 'Agt')
scale_index <- c(rep("scale 1",9), rep("scale 2", 3))
twocoordinate(ppar, scale_index)


peroxisomal_lipid <- c('Acox2', 'Slc27a2', 'Idh1', 'Phyh', 'Scp2', 'Amacr')
scale_index <- c(rep("scale 1",3), rep("scale 2", 12), rep("scale 1", 3))
twocoordinate(peroxisomal_lipid, scale_index)


ppara_activate_ge <- c('Cyp7a1', 'Apoa5', 'Fabp1', 'Ppargc1b', 'Abcb4', 'Ppargc1a', 'Ppara', 'Tead4', 'Ncoa1', 'Apoa1', 'Apoa2', 'Agt', 'Pparg', 'Slc27a1', 'Ctgf', 'Gos2', 'Alas1', 'Tead1', 'Trib3', 'Hmgcs2', 'Acadm', 'Yap1', 'Cpt2', 'Rxra', 'Nr1d1')
scale_index <- c(rep("scale 2",6), rep("scale 1", 3), rep("scale 2", 9), rep("scale 1", 6), rep("scale 2", 3), rep("scale 1", 3), rep("scale 2", 3), rep("scale 1", 3), rep("scale 2", 3), rep("scale 1", 6), rep("scale 2", 6), rep("scale 1", 3), rep("scale 2", 15), rep("scale 1", 3))
twocoordinate(ppara_activate_ge, scale_index)


bile_salt <- c('Cyp7a1', 'Baat', 'Slc27a5', 'Slc10a1', 'Acox2', 'Abcb11', 'Cyp8b1', 'Slc27a2', 'Akr1d1', 'Cyp7b1', 'Alb', 'Cyp27a1', 'Hsd3b7')
scale_index <- c(rep("scale 1",9), rep("scale 2", 3), rep("scale 1", 9), rep("scale 2", 3), rep("scale 1", 3), rep("scale 2", 3), rep("scale 1", 9))
twocoordinate(bile_salt, scale_index)


lipid_transport <- c('Apof', 'Apoc3', 'Apoa1', 'Apoa2', 'Lcat', 'Slco2a1', 'Ldlr', 'Ppara', 'Apoe', 'Tspo')
scale_index <- c(rep("scale 2",3), rep("scale 1", 15), rep("scale 2", 3), rep("scale 1", 9))
twocoordinate(lipid_transport, scale_index)

#### BROWN FAT ####
brown_fat <- c('Ucp1', 'Tspan18', 'P2rx5', 'Lhx8', 'Pat2', 'Ebf3', 'Prdm16', 'Ppargc1a', 'Eva', 'Fbxo31', 'Pdk4', 'Acot2', 'Hsbp7', 'Slc29a1', 'Oplah' )
scale_index <- c(rep("scale 1", 3),rep("scale 2", 21), rep("scale 1", 3), rep("scale 2", 9))
twocoordinate(brown_fat, scale_index)

##### WHITE FAT ########
white_fat <- c("Slc7a10", "Tmem26", "Shox2", "Hoxc8","Hoxc9", "Adipoq", "Fbxo31", "Fabp3", "Mpzl2")
scale_index <- c(rep("scale 1", 3),rep("scale 2", 3), rep("scale 1", 3), rep("scale 2", 12), rep("scale 1",3), rep("scale 3",3))
twocoordinate(white_fat, scale_index)

##### BEIGE FAT #######
beige_fat <- c('Tbx1', 'Tmem26', 'Tnfrsf9', 'Irx3', 'Irx5', 'Klhl13', 'Cd40','Ear2','Cd137','Sp100','Slc27a1', 'Pat2')
scale_index <- c(rep("scale 1", 6),rep("scale 2", 3), rep("scale 1", 3), rep("scale 3", 3), rep("scale 2", 3), rep("scale 1",3), rep("scale 2", 9))
twocoordinate(beige_fat, scale_index)

```


The data used is in the file **`r filename`**.  This file was most recently processed on ```r date()```.


Session Information
---------------------

```{r session-information}
sessionInfo()
```
