Heatmaps for DPSC Analysis
========================================================

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='figures/',
                      echo=FALSE, warning=FALSE, message=FALSE)
```

```{r setup, echo=FALSE}
input_file <- "../data/processed/rpkm_table.csv"
sample_mapping_file <- "../data/raw/sample_mapping.csv"
liver_results_file <- "../data/processed/Liver_DESeqResultsProteinCodingOnly.csv"
wat_results_file <- "../data/processed/WAT_DESeqResultsProteinCodingOnly.csv"
```

This file uses the RPKM counts table found in `r input_file` to calcualte a heatmap.  This script was most recently run on `r date()`.

```{r data-entry, echo=FALSE}
rpkm.counts <- read.csv(input_file, row.names='X')
names(rpkm.counts) <- sub(".txt", "", names(rpkm.counts))

mapping.data <- read.csv(sample_mapping_file, row.names='Sample')

mapping.data$Diet <- as.factor(mapping.data$Diet)
mapping.data$Diet <- relevel(mapping.data$Diet, ref="Normal")

mapping.data$Treatment <- ifelse(mapping.data$Treatment=='vehicle', 'vehicle', 'GTX')
mapping.data$Treatment <- as.factor(mapping.data$Treatment)
mapping.data$Treatment <- relevel(mapping.data$Treatment, ref="vehicle")

liver.mapping.data <- mapping.data[mapping.data$Tissue=="Liver",]
wat.mapping.data <- mapping.data[mapping.data$Tissue=="WAT",]

ordered.mapping.data <- mapping.data[order(mapping.data$Tissue, mapping.data$Treatment),]

ordered.rpkm.data <- rpkm.counts[,rownames(ordered.mapping.data)]

rpkm.avg.data <- cbind(rowMeans(ordered.rpkm.data[,1:3]),rowMeans(ordered.rpkm.data[,4:6]),rowMeans(ordered.rpkm.data[,7:9]),
                       rowMeans(ordered.rpkm.data[,10:12]),rowMeans(ordered.rpkm.data[,13:15]),rowMeans(ordered.rpkm.data[,16:18]))
colnames(rpkm.avg.data) <- c("LNV", "LHV", "LHG", "WNV", "WHV", "WHG")

```


Analysis of All Genes Combined
-------------------------------
```{r all-heatmap, dev=c('png','pdf')}
library(gplots)
library(RColorBrewer,quietly=TRUE)
library(Heatplus)
library(heatmap.plus)
bars <- brewer.pal(3, "Set1")
diet.bars <- brewer.pal(3, "Set2")

color.map <- function(x) if(x=='vehicle'){ bars[1] } else {
  if(x=='GTX'){bars[2]} else {
  if(x=='Normal'){diet.bars[1]} else{
    diet.bars[2]
    }
  }
}


treatment.colors <- as.matrix(sapply(ordered.mapping.data$Treatment, FUN=color.map))
diet.colors <- as.matrix(sapply(ordered.mapping.data$Diet, FUN=color.map))
clab <- matrix(nrow=18, ncol=2)
clab[,1] <- treatment.colors
clab[,2] <- diet.colors

heatmap.colors <- brewer.pal(11, "BrBG")
#heatmap.colors <- colorRampPalette(c("brown", "green"), space = "rgb")(3)

liver_deseq_results <- read.csv(liver_results_file, row.names='Row.names')
liver.sig.genes <- rownames(subset(liver_deseq_results, padj.GTXvsVehicle<0.05))
wat_deseq_results <- read.csv(wat_results_file, row.names='Row.names')
wat.sig.genes <- rownames(subset(wat_deseq_results, padj.GTXvsVehicle<0.05))
sig.genes <- union(liver.sig.genes, wat.sig.genes)
sig.genes <- unique(sig.genes)

all.sig.df <- ordered.rpkm.data[sig.genes,]
normalized.sig.all <- sweep(all.sig.df, 1, rowMeans(all.sig.df), '/')
all.sig.matrix <- as.matrix(normalized.sig.all[complete.cases(normalized.sig.all),])
dnd = list(Row=list(status="hidden"), Col=list(status="no"))
plot(regHeatmap(all.sig.matrix, dendrogram=dnd, legend=2, col=heat.colors, breaks=-3:3))
corrdist = function(x) as.dist(1-cor(t(x)))
hclust.avl = function(x) hclust(x, method="average")
reg3 <- regHeatmap(all.sig.matrix, legend=2, dendrogram=dnd, 
                   col=heatmap.colors, breaks=-2:2)
map <- annHeatmap2(all.sig.matrix, dendrogram=dnd, ann=list(Col=list(data=ordered.mapping.data)), col=g2r.colors)
plot(map)

heatmap.plus(all.sig.matrix, cexCol=0.5, cexRow=0.5, 
          main="Analysis of All Genes Together",
          ColSideColors=clab, col=heatmap.colors, 
          dendrogram='none', Colv=NA, Rowv=NULL, scale='row')
```

Analysis of GTX in Liver
---------------------------------------------------

```{r Liver_GTXvsVehicle, dev=c('png','pdf')}
liver_deseq_results <- read.csv(liver_results_file, row.names='Row.names')
sig.genes <- rownames(subset(liver_deseq_results, padj.GTXvsVehicle<0.05))
liver.sig.df <- ordered.rpkm.data[sig.genes,1:9]

liver.normalized.sig.df <- sweep(liver.sig.df, 1, rowMeans(liver.sig.df), '/')
sig.matrix <- as.matrix(liver.normalized.sig.df[complete.cases(liver.normalized.sig.df),])

map <- annHeatmap(sig.matrix, dendrogram=dnd, ann=list(Col=list(data=liver.mapping.data)), col=g2r.colors)
plot(map)
```

Analysis of HF diet effect on Liver
---------------------------------------------------

```{r Liver_HFvsNormal, dev=c('png','pdf')}
diet.sig.genes <- rownames(subset(liver_deseq_results, padj.HighFatvsNormal<0.05))
liver.sig.diet <- ordered.rpkm.data[diet.sig.genes,1:9]

liver.normalized.sig.diet <- sweep(liver.sig.diet, 1, rowMeans(liver.sig.diet), '/')
diet.sig.matrix <- as.matrix(liver.normalized.sig.diet[complete.cases(liver.normalized.sig.diet),])

diet.map <- annHeatmap(diet.sig.matrix, dendrogram=dnd, ann=list(Col=list(data=liver.mapping.data)), col=g2r.colors)
plot(diet.map)
```

Analysis of GTX vs vehicle in WAT
---------------------------------------------------

```{r WAT_GTXvsVehicle, dev=c('png','pdf')}
wat_deseq_results <- read.csv(wat_results_file, row.names='Row.names')
wat.sig.genes <- rownames(subset(wat_deseq_results, padj.GTXvsVehicle<0.05))
wat.sig.df <- ordered.rpkm.data[wat.sig.genes,10:18]

wat.normalized.sig.df <- sweep(wat.sig.df, 1, rowMeans(wat.sig.df), '/')
wat.sig.matrix <- as.matrix(wat.normalized.sig.df[complete.cases(wat.normalized.sig.df),])

wat.map <- annHeatmap(wat.sig.matrix, dendrogram=dnd, ann=list(Col=list(data=wat.mapping.data)), col=g2r.colors)
plot(wat.map)
```

Analysis of HF diet in WAT
---------------------------------------------------

```{r WAT_HFvsNormal, dev=c('png','pdf')}
wat.sig.genes <- rownames(subset(wat_deseq_results, padj.HighFatvsNormal<0.05))
wat.sig.diet <- ordered.rpkm.data[wat.sig.genes,10:18]

wat.normalized.sig.diet <- sweep(wat.sig.diet, 1, rowMeans(wat.sig.diet), '/')
wat.sig.diet <- as.matrix(wat.normalized.sig.diet[complete.cases(wat.normalized.sig.diet),])

wat.map <- annHeatmap(wat.sig.diet, dendrogram=dnd, ann=list(Col=list(data=wat.mapping.data)), col=g2r.colors)
plot(wat.map)
```



Analysis of All Genes Combined using Average Counts
-------------------------------
```{r Liver_WAT_heatmap_average, dev=c('png','pdf')}
all.sig.df <- rpkm.avg.data[sig.genes,]
normalized.sig.all <- sweep(all.sig.df, 1, rowMeans(all.sig.df), '/')
all.sig.matrix <- as.matrix(normalized.sig.all[complete.cases(normalized.sig.all),])
dnd = list(Row=list(status="hidden"), Col=list(status="no"))
plot(regHeatmap(all.sig.matrix, dendrogram=dnd, legend=2, col=g2r.colors, breaks=-3:3))
corrdist = function(x) as.dist(1-cor(t(x)))
hclust.avl = function(x) hclust(x, method="average")
map <- annHeatmap2(all.sig.matrix, dendrogram=dnd, col=g2r.colors,
                   legend = 3,labels = list(Col = list(nrow = 12)))
plot(map)

heatmap.plus(all.sig.matrix, cexCol=0.5, cexRow=1, 
          main="All Sig Genes in Liver or WAT in average",
          col=heatmap.colors, 
          Colv=F, Rowv=F, scale='row', trace='none', density.info="none")
```

Analysis of GTX in Liver Average
---------------------------------------------------

```{r Liver_GTXvsVehicle_avg, dev=c('png','pdf')}
liver.mapping.sub <- data.frame(Tissue=rep("Liver",3), Diet=c("Normal", "High Fat", "High Fat"), Treatment=c("Vehicle", "Vehicle", "GTX"))
sig.genes <- rownames(subset(liver_deseq_results, padj.GTXvsVehicle<0.05))
liver.sig.df <- rpkm.avg.data[sig.genes,1:3]

liver.normalized.sig.df <- sweep(liver.sig.df, 1, rowMeans(liver.sig.df), '/')
sig.matrix <- as.matrix(liver.normalized.sig.df[complete.cases(liver.normalized.sig.df),])

map <- annHeatmap(sig.matrix, dendrogram=dnd, ann=list(Col=list(data=liver.mapping.sub)), col=g2r.colors,
                  legend = 3,labels = list(Col = list(nrow = 12)))
plot(map)

```

Analysis of HF diet effect on Liver Average
---------------------------------------------------

```{r Liver_HFvsNormal_avg, dev=c('png','pdf')}
diet.sig.genes <- rownames(subset(liver_deseq_results, padj.HighFatvsNormal<0.05))
liver.sig.diet <- rpkm.avg.data[diet.sig.genes,1:3]

liver.normalized.sig.diet <- sweep(liver.sig.diet, 1, rowMeans(liver.sig.diet), '/')
diet.sig.matrix <- as.matrix(liver.normalized.sig.diet[complete.cases(liver.normalized.sig.diet),])

diet.map <- annHeatmap(diet.sig.matrix, dendrogram=dnd, ann=list(Col=list(data=liver.mapping.sub)), col=g2r.colors,  legend = 3,labels = list(Col = list(nrow = 12)))
plot(diet.map)
```

Analysis of GTX vs vehicle in WAT Average
---------------------------------------------------

```{r WAT_GTXvsVehicle_avg, dev=c('png','pdf')}
wat_deseq_results <- read.csv(wat_results_file, row.names='Row.names')
wat.sig.genes <- rownames(subset(wat_deseq_results, padj.GTXvsVehicle<0.05))
wat.sig.df <- rpkm.avg.data[wat.sig.genes,4:6]

wat.mapping.sub <- data.frame(Tissue=rep("WAT",3), Diet=c("Normal", "High Fat", "High Fat"), Treatment=c("Vehicle", "Vehicle", "GTX"))

wat.normalized.sig.df <- sweep(wat.sig.df, 1, rowMeans(wat.sig.df), '/')
wat.sig.matrix <- as.matrix(wat.normalized.sig.df[complete.cases(wat.normalized.sig.df),])

wat.map <- annHeatmap(wat.sig.matrix, dendrogram=dnd, ann=list(Col=list(data=wat.mapping.sub)), 
                      col = g2r.colors,
                      legend = 3,labels = list(Col = list(nrow = 12)))
plot(wat.map)
```

Analysis of HF diet in WAT Average
---------------------------------------------------

```{r WAT_HFvsNormal_avg, dev=c('png','pdf')}
wat.sig.genes <- rownames(subset(wat_deseq_results, padj.HighFatvsNormal<0.05))
wat.sig.diet <- rpkm.avg.data[wat.sig.genes,4:6]

wat.normalized.sig.diet <- sweep(wat.sig.diet, 1, rowMeans(wat.sig.diet), '/')
wat.sig.diet <- as.matrix(wat.normalized.sig.diet[complete.cases(wat.normalized.sig.diet),])

wat.map <- annHeatmap(wat.sig.diet, dendrogram=dnd, ann=list(Col=list(data=wat.mapping.sub)), 
                      col = g2r.colors,
                      legend = 3,labels = list(Col = list(nrow = 12)))
plot(wat.map)
```



Session Information
-------------------

```{r session-info}
sessionInfo()
```
